-- ========================================
-- SOIA - Setup Completo do Banco de Dados
-- ========================================

-- 1. CRIAR TABELA gerenciamento_ai (se não existir)
CREATE TABLE IF NOT EXISTS public.gerenciamento_ai (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nome_agente text NULL,
  prompt_atual text NULL,
  prompt_backup text NULL,
  data_atualizacao timestamp without time zone NULL,
  fluxo_agente text NULL,
  CONSTRAINT gerenciamento_ai_pkey PRIMARY KEY (id)
);

-- 2. POLÍTICAS RLS para gerenciamento_ai
ALTER TABLE public.gerenciamento_ai ENABLE ROW LEVEL SECURITY;

-- Drop políticas antigas se existirem
DROP POLICY IF EXISTS "Enable read access for all users" ON public.gerenciamento_ai;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.gerenciamento_ai;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.gerenciamento_ai;

-- Criar novas políticas
CREATE POLICY "Enable read access for all users"
  ON public.gerenciamento_ai FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Enable insert access for all users"
  ON public.gerenciamento_ai FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Enable update access for all users"
  ON public.gerenciamento_ai FOR UPDATE
  TO public
  USING (true);

-- 3. INSERIR DADOS DE EXEMPLO

-- Limpar dados antigos (opcional)
-- DELETE FROM public.gerenciamento_ai;

-- Inserir agente de IA
INSERT INTO public.gerenciamento_ai (nome_agente, prompt_atual, prompt_backup, data_atualizacao, fluxo_agente)
VALUES (
  'SOIA - Agente Principal',
  'Você é a SOIA, uma assistente de inteligência artificial especializada em e-commerce e atendimento ao cliente. Seu objetivo é responder perguntas sobre produtos, auxiliar em pós-venda e fornecer informações precisas e úteis aos clientes.',
  'Sistema de backup: Responder de forma educada e solicitar que o cliente aguarde atendimento humano.',
  now(),
  'ativo'
) ON CONFLICT DO NOTHING;

-- 4. VERIFICAR SE OUTRAS TABELAS PRECISAM DE RLS

-- Para clientes
ALTER TABLE IF EXISTS public.clientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.clientes;
CREATE POLICY "Enable read for all"
  ON public.clientes FOR SELECT
  TO public
  USING (true);

-- Para mercadolivre_produtos
ALTER TABLE IF EXISTS public.mercadolivre_produtos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.mercadolivre_produtos;
CREATE POLICY "Enable read for all"
  ON public.mercadolivre_produtos FOR SELECT
  TO public
  USING (true);

-- Para mercadolivre_registro_comentarios
ALTER TABLE IF EXISTS public.mercadolivre_registro_comentarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.mercadolivre_registro_comentarios;
CREATE POLICY "Enable read for all"
  ON public.mercadolivre_registro_comentarios FOR SELECT
  TO public
  USING (true);

-- Para mercadolivre_registro_msgposvenda
ALTER TABLE IF EXISTS public.mercadolivre_registro_msgposvenda ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.mercadolivre_registro_msgposvenda;
CREATE POLICY "Enable read for all"
  ON public.mercadolivre_registro_msgposvenda FOR SELECT
  TO public
  USING (true);

-- Para registro_notificacao_mercadolivre
ALTER TABLE IF EXISTS public.registro_notificacao_mercadolivre ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.registro_notificacao_mercadolivre;
CREATE POLICY "Enable read for all"
  ON public.registro_notificacao_mercadolivre FOR SELECT
  TO public
  USING (true);

-- Para registros_notificacao
ALTER TABLE IF EXISTS public.registros_notificacao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.registros_notificacao;
CREATE POLICY "Enable read for all"
  ON public.registros_notificacao FOR SELECT
  TO public
  USING (true);

-- Para n8n_chat_histories
ALTER TABLE IF EXISTS public.n8n_chat_histories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read for all" ON public.n8n_chat_histories;
CREATE POLICY "Enable read for all"
  ON public.n8n_chat_histories FOR SELECT
  TO public
  USING (true);

-- 5. DADOS DE EXEMPLO (opcional - para testes)

-- Exemplo de comentário pré-venda
INSERT INTO public.mercadolivre_registro_comentarios (
  id_produto_ml,
  pergunta,
  resposta_ia,
  data_pergunta
)
VALUES (
  'MLB123456789',
  'Qual o prazo de entrega?',
  'O prazo de entrega é de 5 a 7 dias úteis após a confirmação do pagamento.',
  now()
) ON CONFLICT DO NOTHING;

-- Exemplo de mensagem pós-venda
INSERT INTO public.mercadolivre_registro_msgposvenda (
  order_id,
  pack_id,
  status_envio
)
VALUES (
  '2000123456789',
  'PACK001',
  true
) ON CONFLICT DO NOTHING;

-- Exemplo de notificação
INSERT INTO public.registro_notificacao_mercadolivre (
  id_mensagem,
  id_cliente,
  id_order,
  status_envio
)
VALUES (
  'MSG001',
  'CLI001',
  '2000123456789',
  'enviado'
) ON CONFLICT DO NOTHING;

-- ========================================
-- FIM DO SCRIPT
-- ========================================

-- Para verificar se tudo funcionou:
SELECT 'gerenciamento_ai' as tabela, COUNT(*) as registros FROM public.gerenciamento_ai
UNION ALL
SELECT 'mercadolivre_registro_comentarios', COUNT(*) FROM public.mercadolivre_registro_comentarios
UNION ALL
SELECT 'mercadolivre_registro_msgposvenda', COUNT(*) FROM public.mercadolivre_registro_msgposvenda
UNION ALL
SELECT 'registro_notificacao_mercadolivre', COUNT(*) FROM public.registro_notificacao_mercadolivre;
