-- ========================================
-- TABELA DE LANDING PAGES / FORMULÁRIOS DE CAPTURA
-- ========================================

-- Criar tabela de landing pages
CREATE TABLE IF NOT EXISTS public.landing_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Identificação
  slug TEXT NOT NULL UNIQUE,
  titulo TEXT NOT NULL,
  descricao TEXT,
  
  -- Configuração dos campos
  campos_habilitados JSONB NOT NULL DEFAULT '["nome", "telefone", "email"]',
  
  -- Mensagem WhatsApp
  mensagem_whatsapp TEXT NOT NULL,
  
  -- Personalização visual
  cor_primaria TEXT DEFAULT '#3B82F6',
  imagem_url TEXT,
  
  -- Status e métricas
  ativo BOOLEAN NOT NULL DEFAULT true,
  total_acessos INTEGER NOT NULL DEFAULT 0,
  total_conversoes INTEGER NOT NULL DEFAULT 0,
  
  -- Rastreamento
  utm_source TEXT,
  utm_campaign TEXT
);

-- Criar índices
CREATE INDEX IF NOT EXISTS idx_landing_pages_slug ON public.landing_pages(slug);
CREATE INDEX IF NOT EXISTS idx_landing_pages_ativo ON public.landing_pages(ativo);

-- Habilitar RLS
ALTER TABLE public.landing_pages ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
DROP POLICY IF EXISTS "Permitir leitura de landing pages ativas" ON public.landing_pages;
CREATE POLICY "Permitir leitura de landing pages ativas" 
  ON public.landing_pages
  FOR SELECT
  USING (ativo = true);

DROP POLICY IF EXISTS "Permitir inserção de landing pages" ON public.landing_pages;
CREATE POLICY "Permitir inserção de landing pages" 
  ON public.landing_pages
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir atualização de landing pages" ON public.landing_pages;
CREATE POLICY "Permitir atualização de landing pages" 
  ON public.landing_pages
  FOR UPDATE
  USING (true);

DROP POLICY IF EXISTS "Permitir exclusão de landing pages" ON public.landing_pages;
CREATE POLICY "Permitir exclusão de landing pages" 
  ON public.landing_pages
  FOR DELETE
  USING (true);

-- Tabela de conversões (rastreamento)
CREATE TABLE IF NOT EXISTS public.landing_page_conversoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  landing_page_id BIGINT NOT NULL REFERENCES public.landing_pages(id) ON DELETE CASCADE,
  cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
  
  -- Dados capturados
  dados_capturados JSONB NOT NULL,
  
  -- Informações de rastreamento
  ip_address TEXT,
  user_agent TEXT,
  utm_source TEXT,
  utm_campaign TEXT,
  
  -- Status do envio
  whatsapp_enviado BOOLEAN DEFAULT false,
  whatsapp_erro TEXT
);

-- Criar índices
CREATE INDEX IF NOT EXISTS idx_conversoes_landing_page ON public.landing_page_conversoes(landing_page_id);
CREATE INDEX IF NOT EXISTS idx_conversoes_cliente ON public.landing_page_conversoes(cliente_id);
CREATE INDEX IF NOT EXISTS idx_conversoes_data ON public.landing_page_conversoes(created_at);

-- Habilitar RLS
ALTER TABLE public.landing_page_conversoes ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
DROP POLICY IF EXISTS "Permitir leitura de conversões" ON public.landing_page_conversoes;
CREATE POLICY "Permitir leitura de conversões" 
  ON public.landing_page_conversoes
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Permitir inserção de conversões" ON public.landing_page_conversoes;
CREATE POLICY "Permitir inserção de conversões" 
  ON public.landing_page_conversoes
  FOR INSERT
  WITH CHECK (true);

-- Função para gerar slug único
CREATE OR REPLACE FUNCTION gerar_slug_unico()
RETURNS TEXT AS $$
DECLARE
  novo_slug TEXT;
  existe BOOLEAN;
BEGIN
  LOOP
    -- Gera slug aleatório de 8 caracteres
    novo_slug := LOWER(substring(md5(random()::text) from 1 for 8));
    
    -- Verifica se já existe
    SELECT EXISTS(SELECT 1 FROM public.landing_pages WHERE slug = novo_slug) INTO existe;
    
    -- Se não existe, retorna
    IF NOT existe THEN
      RETURN novo_slug;
    END IF;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Inserir exemplo de landing page
INSERT INTO public.landing_pages (
  slug,
  titulo,
  descricao,
  campos_habilitados,
  mensagem_whatsapp,
  cor_primaria
) VALUES (
  'exemplo',
  'Cadastro de Interesse',
  'Preencha o formulário abaixo para receber mais informações',
  '["nome", "telefone", "email", "cidade"]',
  'Olá {nome}! Recebemos seu cadastro e entraremos em contato em breve. 🚀',
  '#3B82F6'
) ON CONFLICT (slug) DO NOTHING;

-- Verificar dados
SELECT 
  id,
  slug,
  titulo,
  ativo,
  total_acessos,
  total_conversoes,
  created_at
FROM public.landing_pages
ORDER BY created_at DESC;
